app: goapp
image: registry.cn-shanghai.aliyuncs.com/d2jvkpn/goapp
registry: github.com/d2jvkpn/goapp

configs:
  # 3011(port) is for local environment
  dev:
    work_path: /root/docker_dev/goapp_dev
    gitBranch: dev
    port: 3012
    api_url: "http://192.168.122.172:3012"

  test:
    work_path: /root/docker_test/goapp_test
    gitBranch: test
    port: 3013
    api_url: ""

  prod:
    work_path: /root/docker_prod/goapp_prod
    gitBranch: master
    port: 3010
    api_url: ""
